// The stored catalog was generated by Python from a row-major NumPy matrix.
// MediaPipe Web exposes the column-major packed matrix. Reusing Python's flat
// offsets (8,9,10,4,0) on Web's buffer reverses yaw. Translate the offsets, not
// the pixels, so both landmark geometry and the pose lookup refer to the same
// unmirrored source image. See the public-photo input regression audit.
export const CATALOG_POSE_CONVENTION = "python-row-major-from-web-column-major-v1";

export function catalogPoseFromWebMatrix(matrix: ArrayLike<number> | null | undefined): [number, number, number] | null {
  if (!matrix || matrix.length !== 16) return null;
  const values = [matrix[0], matrix[1], matrix[2], matrix[6], matrix[10]];
  if (!values.every(Number.isFinite)) return null;
  return [
    Math.atan2(-matrix[2], Math.hypot(matrix[6], matrix[10])) / (Math.PI / 2),
    Math.atan2(matrix[6], matrix[10]) * 1.4 / (Math.PI / 2),
    Math.atan2(matrix[1], matrix[0]) / (Math.PI / 2),
  ];
}
