#!/usr/bin/env python3
"""Collect CC-licensed real-photo candidates for weak facial-action profiles.

The collector is deliberately source- and metadata-conservative. It searches
Openverse and Wikimedia Commons, accepts only redistributable licenses, limits
Openverse to photograph-oriented providers, and rejects metadata associated
with renders, generated people, illustration, sculpture, mannequins, dolls, or
other non-photographic subjects.

Search text is never trusted as a facial-action label. Every retained image is
measured again by the normal MediaPipe catalog builder and then classified by
the strict Clean Core v3 single-factor policy.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import html
import io
import json
import random
import re
import time
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any, Iterable

from PIL import Image, ImageOps, ImageStat

USER_AGENT = "ManyFacesRealExpressionCollector/1.0 (https://github.com/ugin-man/many-faces-beta)"
OPENVERSE_ENDPOINT = "https://api.openverse.org/v1/images/"
COMMONS_ENDPOINT = "https://commons.wikimedia.org/w/api.php"

ALLOWED_LICENSES = {"cc0", "pdm", "by", "by-sa"}
DEFAULT_OPENVERSE_SOURCES = {"flickr", "wikimedia", "stocksnap", "nappy"}

NON_PHOTO_TERMS = {
    "3d render", "3-d render", "3d-render", "rendered face", "cgi", "computer generated",
    "computer-generated", "synthetic human", "synthetic face", "virtual human", "metahuman",
    "digital human", "ai generated", "ai-generated", "generated by ai", "stable diffusion",
    "midjourney", "dall-e", "dalle", "flux ai", "artificial intelligence art", "avatar",
    "video game character", "game character", "character model", "face model", "3d model",
    "illustration", "illustrated", "drawing", "sketch", "painting", "painted portrait",
    "digital art", "concept art", "cartoon", "comic", "anime", "manga", "vector art",
    "sculpture", "statue", "bust", "wax figure", "waxwork", "mannequin", "dummy",
    "doll", "puppet", "mask", "face mask", "toy figure", "action figure", "figurine",
    "mugshot generator", "this person does not exist", "gan face", "deepfake",
}

HTML_TAG = re.compile(r"<[^>]+>")
SPACE = re.compile(r"\s+")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    parser.add_argument("--queries", type=Path, required=True)
    parser.add_argument("--max-images", type=int, default=8_000)
    parser.add_argument("--openverse-pages", type=int, default=12)
    parser.add_argument("--commons-pages", type=int, default=8)
    parser.add_argument("--workers", type=int, default=16)
    parser.add_argument("--seed", type=int, default=20260824)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def clean_text(value: Any) -> str:
    text = html.unescape(str(value or ""))
    text = HTML_TAG.sub(" ", text)
    return SPACE.sub(" ", text).strip()


def normalize_license(value: Any) -> str:
    text = clean_text(value).lower().replace("_", "-")
    if "public domain" in text or text in {"pdm", "publicdomain"}:
        return "pdm"
    if "cc0" in text or "zero" in text:
        return "cc0"
    if "by-sa" in text or "by sa" in text:
        return "by-sa"
    if text == "by" or text.startswith("cc by") or "/by/" in text:
        return "by"
    return text


def metadata_is_non_photo(*values: Any) -> bool:
    text = " ".join(clean_text(value).lower() for value in values if value is not None)
    return any(term in text for term in NON_PHOTO_TERMS)


def request_json(url: str, retries: int = 5) -> dict[str, Any]:
    last_error: Exception | None = None
    for attempt in range(retries):
        try:
            request = urllib.request.Request(
                url,
                headers={"User-Agent": USER_AGENT, "Accept": "application/json"},
            )
            with urllib.request.urlopen(request, timeout=45) as response:
                return json.load(response)
        except Exception as error:  # network dependent
            last_error = error
            time.sleep(min(12.0, 1.25 * (attempt + 1) ** 2))
    raise RuntimeError(f"request failed after {retries} attempts: {url}") from last_error


def load_spec(path: Path) -> tuple[str, list[str], list[str], set[str]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("query specification must be an object")
    group = clean_text(payload.get("group") or path.stem)
    queries = [clean_text(value) for value in payload.get("queries", []) if clean_text(value)]
    categories = [clean_text(value) for value in payload.get("commonsCategories", []) if clean_text(value)]
    sources = {
        clean_text(value).lower()
        for value in payload.get("allowedOpenverseSources", sorted(DEFAULT_OPENVERSE_SOURCES))
        if clean_text(value)
    }
    if not queries and not categories:
        raise ValueError(f"{path}: no queries or Commons categories")
    return group, queries, categories, sources


def openverse_candidates(
    query: str,
    pages: int,
    allowed_sources: set[str],
    group: str,
) -> Iterable[dict[str, Any]]:
    for page in range(1, pages + 1):
        base = {
            "q": query,
            "page": page,
            "page_size": 80,
            "license": "cc0,pdm,by,by-sa",
            "mature": "false",
            "category": "photograph",
        }
        url = f"{OPENVERSE_ENDPOINT}?{urllib.parse.urlencode(base)}"
        try:
            payload = request_json(url)
        except RuntimeError:
            # Older Openverse deployments may not accept category. Retry with
            # the same conservative provider and metadata filters.
            base.pop("category", None)
            try:
                payload = request_json(f"{OPENVERSE_ENDPOINT}?{urllib.parse.urlencode(base)}")
            except RuntimeError:
                break
        results = payload.get("results") or []
        if not results:
            break
        for item in results:
            source = clean_text(item.get("source") or item.get("provider")).lower()
            provider = clean_text(item.get("provider")).lower()
            if allowed_sources and source not in allowed_sources and provider not in allowed_sources:
                continue
            license_code = normalize_license(item.get("license"))
            if license_code not in ALLOWED_LICENSES:
                continue
            title = clean_text(item.get("title") or query)
            description = clean_text(item.get("description"))
            creator = clean_text(item.get("creator") or "Unknown")
            if metadata_is_non_photo(title, description, creator, source, provider):
                continue
            image_url = item.get("url") or item.get("thumbnail")
            landing = item.get("foreign_landing_url") or item.get("detail_url")
            if not image_url or not landing:
                continue
            yield {
                "source_id": f"openverse:{item.get('id')}",
                "source_name": "Openverse",
                "provider": provider or source,
                "source_url": str(landing),
                "image_url": str(image_url),
                "title": title,
                "description": description,
                "creator": creator,
                "creator_url": str(item.get("creator_url") or ""),
                "license": license_code,
                "license_url": str(item.get("license_url") or ""),
                "query": query,
                "target_group": group,
                "source_kind": "real-photo-candidate",
                "modified": False,
            }
        if not payload.get("next"):
            break


def commons_search_candidates(query: str, pages: int, group: str) -> Iterable[dict[str, Any]]:
    offset: int | None = None
    for _ in range(pages):
        params: dict[str, Any] = {
            "action": "query",
            "format": "json",
            "formatversion": 2,
            "generator": "search",
            "gsrsearch": f"{query} filetype:bitmap",
            "gsrnamespace": 6,
            "gsrlimit": 50,
            "prop": "imageinfo",
            "iiprop": "url|extmetadata|mime|size",
            "iiurlwidth": 1600,
        }
        if offset is not None:
            params["gsroffset"] = offset
        try:
            payload = request_json(f"{COMMONS_ENDPOINT}?{urllib.parse.urlencode(params)}")
        except RuntimeError:
            break
        pages_data = payload.get("query", {}).get("pages", [])
        if not pages_data:
            break
        yield from commons_pages_to_candidates(pages_data, query, group)
        offset = payload.get("continue", {}).get("gsroffset")
        if offset is None:
            break


def commons_category_candidates(category: str, pages: int, group: str) -> Iterable[dict[str, Any]]:
    title = category if category.lower().startswith("category:") else f"Category:{category}"
    continuation: str | None = None
    for _ in range(pages):
        params: dict[str, Any] = {
            "action": "query",
            "format": "json",
            "formatversion": 2,
            "generator": "categorymembers",
            "gcmtitle": title,
            "gcmnamespace": 6,
            "gcmlimit": 50,
            "prop": "imageinfo",
            "iiprop": "url|extmetadata|mime|size",
            "iiurlwidth": 1600,
        }
        if continuation:
            params["gcmcontinue"] = continuation
        try:
            payload = request_json(f"{COMMONS_ENDPOINT}?{urllib.parse.urlencode(params)}")
        except RuntimeError:
            break
        pages_data = payload.get("query", {}).get("pages", [])
        if not pages_data:
            break
        yield from commons_pages_to_candidates(pages_data, title, group)
        continuation = payload.get("continue", {}).get("gcmcontinue")
        if not continuation:
            break


def commons_pages_to_candidates(
    pages_data: list[dict[str, Any]],
    query: str,
    group: str,
) -> Iterable[dict[str, Any]]:
    for page in pages_data:
        info_list = page.get("imageinfo") or []
        if not info_list:
            continue
        info = info_list[0]
        mime = clean_text(info.get("mime"))
        if mime and not mime.startswith("image/"):
            continue
        width = int(info.get("width") or 0)
        height = int(info.get("height") or 0)
        if width and height and min(width, height) < 256:
            continue
        meta = info.get("extmetadata") or {}
        meta_value = lambda key: clean_text((meta.get(key) or {}).get("value"))
        license_code = normalize_license(meta_value("LicenseShortName"))
        if license_code not in ALLOWED_LICENSES:
            continue
        title = clean_text(page.get("title") or query)
        description = meta_value("ImageDescription") or meta_value("ObjectName")
        categories = meta_value("Categories")
        creator = meta_value("Artist") or "Unknown"
        if metadata_is_non_photo(title, description, categories, creator):
            continue
        image_url = info.get("thumburl") or info.get("url")
        landing = info.get("descriptionurl")
        if not image_url or not landing:
            continue
        yield {
            "source_id": f"commons:{page.get('pageid')}",
            "source_name": "Wikimedia Commons",
            "provider": "wikimedia",
            "source_url": str(landing),
            "image_url": str(image_url),
            "title": title,
            "description": description,
            "creator": creator,
            "creator_url": "",
            "license": license_code,
            "license_url": meta_value("LicenseUrl"),
            "query": query,
            "target_group": group,
            "source_kind": "real-photo-candidate",
            "modified": False,
        }


def download_bytes(url: str, retries: int = 4) -> bytes:
    last_error: Exception | None = None
    for attempt in range(retries):
        try:
            request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
            with urllib.request.urlopen(request, timeout=50) as response:
                content_type = response.headers.get("Content-Type", "")
                if content_type and "image" not in content_type.lower():
                    raise ValueError(f"not an image: {content_type}")
                data = response.read(24 * 1024 * 1024 + 1)
            if len(data) > 24 * 1024 * 1024:
                raise ValueError("image exceeds 24 MiB")
            return data
        except Exception as error:  # network dependent
            last_error = error
            time.sleep(0.9 * (attempt + 1))
    raise RuntimeError(f"download failed: {url}") from last_error


def normalize_image(data: bytes) -> tuple[bytes, int, int]:
    with Image.open(io.BytesIO(data)) as opened:
        image = ImageOps.exif_transpose(opened).convert("RGB")
        if min(image.size) < 256:
            raise ValueError("image is too small")
        # Very low-entropy files are commonly icons, diagrams, or flat artwork.
        gray = image.convert("L").resize((128, 128), Image.Resampling.BILINEAR)
        if ImageStat.Stat(gray).rms[0] < 12 or gray.entropy() < 3.8:
            raise ValueError("image lacks photographic detail")
        image.thumbnail((1600, 1600), Image.Resampling.LANCZOS)
        output = io.BytesIO()
        image.save(output, format="WEBP", quality=92, method=6)
        return output.getvalue(), image.width, image.height


def stage_one(item: dict[str, Any], images: Path) -> dict[str, Any]:
    raw = download_bytes(item["image_url"])
    normalized, width, height = normalize_image(raw)
    digest = hashlib.sha256(normalized).hexdigest()
    filename = f"{digest}.webp"
    path = images / filename
    if not path.exists():
        path.write_bytes(normalized)
    return {
        **item,
        "filename": filename,
        "sha256": digest,
        "width": width,
        "height": height,
    }


def write_metadata(output: Path, rows: list[dict[str, Any]]) -> None:
    fields = [
        "filename", "file", "path", "relative_path", "id", "source_id", "sourceId",
        "name", "title", "description", "source_name", "sourceName", "source_url",
        "sourceUrl", "provider", "creator", "creator_url", "license", "license_url",
        "licenseUrl", "query", "target_group", "source_kind", "sourceKind", "modified",
        "modification", "sha256", "width", "height",
    ]
    with (output / "metadata.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            filename = row["filename"]
            normalized = {
                **row,
                "file": filename,
                "path": f"images/{filename}",
                "relative_path": f"images/{filename}",
                "id": row["source_id"],
                "sourceId": row["source_id"],
                "name": row["title"],
                "sourceName": row["source_name"],
                "sourceUrl": row["source_url"],
                "licenseUrl": row["license_url"],
                "sourceKind": row["source_kind"],
                "modification": "",
            }
            writer.writerow({field: normalized.get(field, "") for field in fields})


def main() -> int:
    args = parse_args()
    output = args.output.resolve()
    if output.exists() and any(output.iterdir()) and not args.overwrite:
        raise SystemExit(f"output directory is not empty: {output}")
    if args.overwrite and output.exists():
        import shutil
        shutil.rmtree(output)
    images = output / "images"
    images.mkdir(parents=True, exist_ok=True)

    group, queries, categories, allowed_sources = load_spec(args.queries.resolve())
    candidates: list[dict[str, Any]] = []
    seen_source: set[str] = set()
    for query in queries:
        for item in openverse_candidates(query, args.openverse_pages, allowed_sources, group):
            if item["source_id"] not in seen_source:
                seen_source.add(item["source_id"])
                candidates.append(item)
        for item in commons_search_candidates(query, args.commons_pages, group):
            if item["source_id"] not in seen_source:
                seen_source.add(item["source_id"])
                candidates.append(item)
    for category in categories:
        for item in commons_category_candidates(category, args.commons_pages, group):
            if item["source_id"] not in seen_source:
                seen_source.add(item["source_id"])
                candidates.append(item)

    random.Random(args.seed).shuffle(candidates)
    rows: list[dict[str, Any]] = []
    hashes: set[str] = set()
    failures: dict[str, int] = {}
    with ThreadPoolExecutor(max_workers=max(1, args.workers)) as executor:
        pending = {executor.submit(stage_one, item, images): item for item in candidates}
        for future in as_completed(pending):
            if len(rows) >= args.max_images:
                for task in pending:
                    task.cancel()
                break
            try:
                row = future.result()
            except Exception as error:  # network/image dependent
                key = type(error).__name__
                failures[key] = failures.get(key, 0) + 1
                continue
            if row["sha256"] in hashes:
                continue
            hashes.add(row["sha256"])
            rows.append(row)

    rows.sort(key=lambda row: (row["query"], row["source_id"]))
    write_metadata(output, rows)
    report = {
        "schemaVersion": 1,
        "group": group,
        "queries": queries,
        "commonsCategories": categories,
        "allowedOpenverseSources": sorted(allowed_sources),
        "sourceCandidates": len(candidates),
        "stagedImages": len(rows),
        "licenses": sorted({row["license"] for row in rows}),
        "providers": dict(sorted({
            provider: sum(1 for row in rows if row.get("provider") == provider)
            for provider in {row.get("provider", "") for row in rows}
        }.items())),
        "downloadFailures": failures,
        "runtimePolicy": "real-photo-candidate-only-v1",
    }
    (output / "source-report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(report, ensure_ascii=False, indent=2))
    if not rows:
        raise SystemExit("no real-photo candidates were staged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
